Repository Code-Dabblers/Ecommerce-Site, pull requests merged in 2020-10, with the labels that each got.

#21 sass demonstration, adding new module, small fixes...
  index.html
  src/JavaScript/index.js
  src/JavaScript/modules/cart.js
  src/JavaScript/modules/homepage.js
  src/JavaScript/modules/product-details.js
  src/JavaScript/modules/product-list.js
  src/JavaScript/modules/search.js
  src/assets/landing-page/main-banner-shoe-img.png
  src/assets/landing-page/purse-1.png
  src/assets/landing-page/purse-2.png
  src/assets/landing-page/purse-3.png
  src/assets/landing-page/shoe-1.png
  src/assets/landing-page/shoe-2.png
  src/assets/landing-page/shoe-3.png
  src/assets/landing-page/shoe-4.png
  src/assets/landing-page/shoe-5.png
  src/assets/landing-page/shoe-6.png
  src/assets/landing-page/shoe-7.png
  src/assets/product-search/purse-1.png
  src/assets/product-search/purse-2.png
  src/assets/product-search/shoe-1.png
  src/assets/product-search/shoe-2.png
  src/assets/product-search/shoe-3.png
  src/assets/product-search/shoe-4.png
  src/assets/product-search/shoe-5.png
  src/assets/product-search/shoe-6.png
  src/assets/single-product-page/purse-1.png
  src/assets/single-product-page/purse-2.png
  src/assets/single-product-page/shoe-1.png
  src/assets/single-product-page/shoe-2.png
  src/assets/single-product-page/shoe-3.png
  src/assets/single-product-page/shoe-4.png
  src/assets/single-product-page/shoe-5.png
  src/assets/single-product-page/shoe-6.png
  src/assets/single-product-page/shoe-7.png
  src/assets/svgs/app-logo.svg
  src/assets/svgs/refund.svg
  src/assets/svgs/shipping.svg
  src/assets/svgs/support.svg
  src/styles/css/style.css
  src/styles/sass/abstracts/_mixins.scss
  src/styles/sass/abstracts/_variables.scss
  src/styles/sass/base/_base.scss
  src/styles/sass/base/_typography.scss
  src/styles/sass/components/_button.scss
  src/styles/sass/layout/_footer.scss
  src/styles/sass/layout/_header.scss
  src/styles/sass/main.scss
  src/styles/sass/pages/_cart.scss
  src/styles/sass/pages/_homepage.scss
  src/styles/sass/pages/_product-details.scss
  src/styles/sass/pages/_product-list.scss
  src/styles/sass/pages/_search.scss
Labels: hackoctoberfest-accepted

#25 Feature/style contrib guidelines
  README.md
  style-guidelines.md
Labels: documentation

#29 Product page design
  src/JavaScript/modules/product-list.js
  src/index.html
  src/styles/sass/main.css
  src/styles/sass/main.css.map
  src/styles/sass/pages/_product-list.scss
Labels: add-feature, hackoctoberfest-accepted

#34 Feature/cart#27
  debug.log
  src/JavaScript/modules/cart.js
  src/styles/sass/abstracts/_mixins.scss
  src/styles/sass/pages/_cart.scss
Labels: hackoctoberfest-accepted

#41 refactor: get rid of unnecessary variables
  src/styles/sass/abstracts/_mixins.scss
  src/styles/sass/abstracts/_variables.scss
  src/styles/sass/layout/_footer.scss
  src/styles/sass/pages/_error404.scss
  src/styles/sass/pages/_homepage.scss
Labels: bug, enhancement

#44 Feature/add responsive product list
  src/JavaScript/modules/product-list.js
  src/styles/sass/pages/_product-list.scss
Labels: enhancement, hackoctoberfest-accepted

#47 Feature/navbar responsiveness#43
  debug.log
  src/JavaScript/index.js
  src/JavaScript/modules/cart.js
  src/index.html
  src/styles/sass/abstracts/_mixins.scss
  src/styles/sass/base/_base.scss
  src/styles/sass/layout/_header.scss
  src/styles/sass/pages/_cart.scss
Labels: hackoctoberfest-accepted

#48 Fixed the alignment issues on the cart page.
  debug.log
  src/styles/sass/pages/_cart.scss
Labels: hackoctoberfest-accepted
